#!/usr/bin/env python
import os
import logging
log = logging.getLogger(os.path.basename(__file__))
from ROOT import TMVA
from brtautau.regressor import Regressor
from brtautau.categories.features import FEATURES 

from rootpy.extern.argparse import ArgumentParser
parser = ArgumentParser()
parser.add_argument('--mode', default='gg', type=str, choices=['VBF', 'gg'])
parser.add_argument('--dry', action='store_true', default=False)
args = parser.parse_args()

## Set the directory where to save the weights file.
(TMVA.gConfig().GetIONames()).fWeightFileDir = './RESULTS/'

log.info("Training begins !")

features = FEATURES
brt_regressor = Regressor(
    './RESULTS/'+ str(args.mode)+'_training_output.root',
    features)

brt_regressor.train(mode=args.mode)
