#!/usr/bin/env python
import os
import datetime
import logging

#log = logging.getLogger(os.path.basename(__file__))
from ROOT import TMVA
from brtautau.regressor import Regressor
from brtautau.categories.features import FEATURES 
from brtautau import *

## Set the directory where to save the weights file.
(TMVA.gConfig().GetIONames()).fWeightFileDir = './RESULTS'

log.info("Training begins !")

my_datetime = datetime.date.today()
my_datetime = my_datetime.strftime("%m%d%Y")
features = FEATURES
brt_regressor = Regressor(
    './RESULTS/'+ str(my_datetime)+'-'+str(args.train_level)+'_' + str(args.train_mode)+'_' + str(args.channel) +'_training_output.root',
    features)
try:
    brt_regressor.train(mode=args.train_mode, level=args.train_level)

except KeyboardInterrupt:
    print "Gracefully terminated by the user"
